name: desk_env
channels:
  - defaults
dependencies:
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - pip=19.2.3=py37_0
  - pylint=2.4.2=py37_0
  - pip:
      - requests==2.18.4
      - Flask==1.1.1
      - pandas==0.25.3
      - matplotlib==3.1.2 
      - wordcloud==1.6.0
      - vaderSentiment==3.2.1
      - asyncio==3.4.3  
      - aiohttp==3.6.2 
   
